local ls = require("luasnip")
local snippet = ls.snippet
local text_node = ls.text_node
local ins_node = ls.insert_node
-- BibTeX entry types

return {

	snippet({ trig = "abv", name = "BibTeX abbreviation" }, {
		text_node("@string{"),
		ins_node(1, "key"),
		text_node(' = "'),
		ins_node(2, "text to abbreviate"),
		text_node('"}'),
	}),

	snippet({ trig = "art", name = "article" }, {
		text_node("@article{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('journal = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('pages = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(10),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "bks", name = "book" }, {
		text_node("@book{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('editor = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('publisher = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('series = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(10),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('edition = "'),
		ins_node(11),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(12),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(13),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "bkl", name = "booklet" }, {
		text_node("@booklet{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('howpublished = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(8),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "ibk", name = "inbook" }, {
		text_node("@inbook{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('editor = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('chapter = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('pages = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('publisher = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(10),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('series = "'),
		ins_node(11),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('type = "'),
		ins_node(12),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(13),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('edition = "'),
		ins_node(14),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(15),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(16),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "inc", name = "incollection" }, {
		text_node("@incollection{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('booktitle = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('publisher = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('editor = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('series = "'),
		ins_node(10),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('type = "'),
		ins_node(11),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('chapter = "'),
		ins_node(12),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('pages = "'),
		ins_node(13),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(14),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('edition = "'),
		ins_node(15),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(16),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(17),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "inp", name = "inproceedings" }, {
		text_node("@inproceedings{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('booktitle = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('editor = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('series = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('pages = "'),
		ins_node(10),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(11),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(12),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('organization = "'),
		ins_node(13),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('edition = "'),
		ins_node(14),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('publisher = "'),
		ins_node(15),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(16),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "man", name = "manual" }, {
		text_node("@manual{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('organization = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('edition = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(9),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "mst", name = "masterthesis" }, {
		text_node("@masterthesis{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('school = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('type = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(9),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "mis", name = "misc" }, {
		text_node("@misc{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('howpublished = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(7),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "phd", name = "phdthesis" }, {
		text_node("@phdthesis{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('school = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('type = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(9),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "pcd", name = "proceeding" }, {
		text_node("@proceedings{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('editor = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('volume = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('series = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('publisher = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(10),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(11),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('organization = "'),
		ins_node(12),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "tec", name = "techreport" }, {
		text_node("@techreport{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('institution = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('type = "'),
		ins_node(6),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('number = "'),
		ins_node(7),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('address = "'),
		ins_node(8),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(9),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(10),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),

	snippet({ trig = "unp", name = "unpublished" }, {
		text_node("@unpublished{"),
		ins_node(1, "key-identifier"),
		text_node(","),
		text_node({ "", "" }),
		text_node("    "),
		text_node('author = "'),
		ins_node(2),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('title = "'),
		ins_node(3),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('note = "'),
		ins_node(4),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('month = "'),
		ins_node(5),
		text_node('",'),
		text_node({ "", "" }),
		text_node("    "),
		text_node('year = "'),
		ins_node(6),
		text_node('"'),
		text_node({ "", "" }),
		text_node("}"),
	}),
}
